# Generated by Django 2.2.24 on 2021-11-16 22:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Введите названия продукта/услуги', max_length=100, verbose_name='Название')),
                ('in_price', models.PositiveIntegerField(default=0, help_text='Введите цену от поставщика продукта/услуги', verbose_name='Себестоимость грн.')),
                ('out_price', models.PositiveIntegerField(default=0, help_text='Введите цену для клиента продукта/услуги', verbose_name='Стоимость грн.')),
                ('detail_number_original', models.CharField(help_text='Введите № детали по каталогу оригинального производителя ', max_length=100, verbose_name='№ детали оригинал')),
                ('detail_manufacturer', models.CharField(help_text='Введите название поставщика детали', max_length=100, verbose_name='поставщик детали')),
                ('detail_number_cross', models.CharField(blank=True, help_text='Введите № детали по "заменителю"', max_length=100, null=True, verbose_name='cross № детали')),
                ('detail_provider', models.CharField(help_text='Введите название поставщика детали', max_length=100, verbose_name='поставщик детали')),
                ('stock', models.PositiveIntegerField(default=1, help_text='Введите количество деталей', verbose_name='кол-во')),
                ('is_available', models.BooleanField(default=False, help_text='для добавления детали на склад поставьте галочку', verbose_name='на склад')),
            ],
            options={
                'verbose_name_plural': 'Детали',
            },
        ),
        migrations.CreateModel(
            name='OilContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(choices=[('1л', '1л'), ('2л', '2л'), ('5л', '5л'), ('10л', '10л'), ('20л', '20л')], help_text='Выберите объём тары', max_length=100, null=True, verbose_name='Объём тары')),
            ],
            options={
                'verbose_name_plural': 'Фасовка масла',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Введите названия продукта/услуги', max_length=100, verbose_name='Название')),
                ('in_price', models.PositiveIntegerField(default=0, help_text='Введите цену от поставщика продукта/услуги', verbose_name='Себестоимость грн.')),
                ('out_price', models.PositiveIntegerField(default=0, help_text='Введите цену для клиента продукта/услуги', verbose_name='Стоимость грн.')),
                ('work_our', models.DecimalField(decimal_places=2, default=1, help_text='Введите количество часов', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='нормо-часы')),
            ],
            options={
                'verbose_name_plural': 'Услуги (работы)',
            },
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Введите названия продукта/услуги', max_length=100, verbose_name='Название')),
                ('in_price', models.PositiveIntegerField(default=0, help_text='Введите цену от поставщика продукта/услуги', verbose_name='Себестоимость грн.')),
                ('out_price', models.PositiveIntegerField(default=0, help_text='Введите цену для клиента продукта/услуги', verbose_name='Стоимость грн.')),
                ('stock_l', models.DecimalField(decimal_places=2, default=1, help_text='Введите количество л', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='кол-во')),
                ('is_available', models.BooleanField(default=False, help_text='для добавления масла на склад поставьте галочку', verbose_name='на склад')),
                ('container', models.OneToOneField(help_text='Выберите тару, в которой поступило масло', on_delete=django.db.models.deletion.CASCADE, related_name='oil', to='products.OilContainer', verbose_name='Тара')),
            ],
            options={
                'verbose_name_plural': 'Масло',
            },
        ),
        migrations.CreateModel(
            name='KitService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Введите названия продукта/услуги', max_length=100, verbose_name='Название')),
                ('in_price', models.PositiveIntegerField(default=0, help_text='Введите цену от поставщика продукта/услуги', verbose_name='Себестоимость грн.')),
                ('out_price', models.PositiveIntegerField(default=0, help_text='Введите цену для клиента продукта/услуги', verbose_name='Стоимость грн.')),
                ('kit_work_ours', models.DecimalField(decimal_places=2, default=1, help_text='Поле заполнится автоматически', max_digits=12, verbose_name='нормо-часы')),
                ('services', models.ManyToManyField(to='products.Service')),
            ],
            options={
                'verbose_name_plural': 'Услуги (работы)',
            },
        ),
    ]
