# Generated by Django 2.2.24 on 2021-11-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oil',
            name='is_available',
            field=models.BooleanField(default=False, help_text='для добавления на склад поставьте галочку', verbose_name='на склад'),
        ),
        migrations.AlterField(
            model_name='oil',
            name='out_price',
            field=models.PositiveIntegerField(default=0, help_text='Поле зааполнится автоматически', verbose_name='Стоимость грн.'),
        ),
        migrations.AlterField(
            model_name='part',
            name='is_available',
            field=models.BooleanField(default=False, help_text='для добавления на склад поставьте галочку', verbose_name='на склад'),
        ),
        migrations.AlterField(
            model_name='part',
            name='out_price',
            field=models.PositiveIntegerField(default=0, help_text='Поле зааполнится автоматически', verbose_name='Стоимость грн.'),
        ),
    ]
