# Generated by Django 2.2.24 on 2021-11-17 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oilcontainer',
            old_name='container',
            new_name='volume',
        ),
        migrations.AddField(
            model_name='oilcontainer',
            name='container_date',
            field=models.DateField(default=datetime.date.today, help_text='Выберите дату', verbose_name='Дата поступления на склад'),
        ),
        migrations.AlterField(
            model_name='kitservice',
            name='services',
            field=models.ManyToManyField(help_text='Выберите работы из которых состоит услуга', to='products.Service', verbose_name='набор работ'),
        ),
    ]
