# Generated by Django 2.2.24 on 2021-11-20 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
        ('products', '0002_auto_20211120_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitservice',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='выберите ЗН', null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.Work_order', verbose_name='ЗН'),
        ),
        migrations.AddField(
            model_name='oil',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='выберите ЗН', null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.Work_order', verbose_name='ЗН'),
        ),
        migrations.AddField(
            model_name='part',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='выберите ЗН', null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.Work_order', verbose_name='ЗН'),
        ),
        migrations.AddField(
            model_name='work',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='выберите ЗН', null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.Work_order', verbose_name='ЗН'),
        ),
    ]
