# Generated by Django 2.2.24 on 2021-11-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211120_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oil',
            options={'verbose_name_plural': 'Масла'},
        ),
        migrations.RemoveField(
            model_name='kitservice',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='oil',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='part',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_order',
        ),
    ]
