# Generated by Django 2.2.24 on 2021-11-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211117_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitservice',
            name='out_price',
            field=models.PositiveIntegerField(default=0, help_text='Поле заполнится автоматически', verbose_name='Стоимость грн.'),
        ),
    ]
