# Generated by Django 2.2.24 on 2021-11-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211117_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitservice',
            name='kit_work_ours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Поле заполнится автоматически', max_digits=12, verbose_name='нормо-часы'),
        ),
    ]
