# Generated by Django 2.2.24 on 2021-11-20 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField(default=datetime.date.today, help_text='Выберите дату', verbose_name='Дата открытия ЗН')),
                ('close_date', models.DateField(blank=True, help_text='Выберите дату', null=True, verbose_name='Дата закрытия ЗН')),
                ('av_price', models.PositiveIntegerField(default=80, help_text='Введите цену ', verbose_name='Цена нормачаса (AV) грн.')),
                ('total_in_price_parts', models.PositiveIntegerField(default=0, help_text='Поле зааполнится автоматически', verbose_name='себестоимость за ЗЧ грн.')),
                ('total_out_price_parts', models.PositiveIntegerField(default=0, help_text='Поле зааполнится автоматически', verbose_name='Стоимость ЗЧ для клиента грн.')),
                ('total_price_services', models.PositiveIntegerField(default=0, help_text='Поле зааполнится автоматически', verbose_name='Стоимость работ грн.')),
                ('total_price', models.PositiveIntegerField(default=0, help_text='Поле зааполнится автоматически', verbose_name='СОбщая сумма грн.')),
                ('car', models.ForeignKey(help_text='Выберите авто, на которое открыт ЗН', on_delete=django.db.models.deletion.CASCADE, to='cars.Car', verbose_name='Автомобиль')),
            ],
        ),
    ]
