# Generated by Django 2.2.24 on 2021-11-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211120_2023'),
        ('cars', '0001_initial'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work_order',
            new_name='WorkOrder',
        ),
    ]
