# Generated by Django 2.2.24 on 2021-11-24 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211124_1446'),
        ('workorders', '0002_auto_20211120_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'verbose_name_plural': 'Заказ-Наряды'},
        ),
        migrations.AddField(
            model_name='workorder',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('in_work', 'в работе'), ('completed', 'закрыт')], default='in_work', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='car',
            field=models.ForeignKey(help_text='Выберите авто, на которое открыт ЗН', on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='cars.Car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='total_price',
            field=models.PositiveIntegerField(default=0, help_text='Поле зааполнится автоматически', verbose_name='Общая сумма грн.'),
        ),
        migrations.CreateModel(
            name='WorOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_service', models.ForeignKey(help_text='Выберите работу(набор работ) по ЗН', on_delete=django.db.models.deletion.CASCADE, related_name='work_order_item_kit_service', to='products.KitService', verbose_name='набор работ')),
                ('oil', models.ForeignKey(help_text='Выберите масло использованное по ЗН', on_delete=django.db.models.deletion.CASCADE, related_name='work_order_item_oil', to='products.Oil', verbose_name='масло')),
                ('part', models.ForeignKey(help_text='Выберите ЗЧ использованную по ЗН', on_delete=django.db.models.deletion.CASCADE, related_name='work_order_item_part', to='products.Part', verbose_name='ЗЧ')),
                ('service', models.ForeignKey(help_text='Выберите работу по ЗН', on_delete=django.db.models.deletion.CASCADE, related_name='work_order_item_service', to='products.Work', verbose_name='работа')),
                ('work_order', models.ForeignKey(help_text='Выберите ЗН', on_delete=django.db.models.deletion.CASCADE, related_name='work_order_item', to='workorders.WorkOrder', verbose_name='ЗН')),
            ],
        ),
    ]
