# Generated by Django 2.2.24 on 2021-11-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_auto_20211124_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wororderitem',
            options={'verbose_name_plural': 'Позиции в ЗН'},
        ),
    ]
