# Generated by Django 2.2.24 on 2021-11-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_auto_20211124_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('in_work', 'в работе'), ('completed', 'закрыт')], default='in_work', max_length=20, verbose_name='Статус ЗН'),
        ),
        migrations.AlterField(
            model_name='wororderitem',
            name='kit_service',
            field=models.ForeignKey(blank=True, help_text='Выберите работу(набор работ) по ЗН', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_order_item_kit_service', to='products.KitService', verbose_name='набор работ'),
        ),
        migrations.AlterField(
            model_name='wororderitem',
            name='oil',
            field=models.ForeignKey(blank=True, help_text='Выберите масло использованное по ЗН', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_order_item_oil', to='products.Oil', verbose_name='масло'),
        ),
        migrations.AlterField(
            model_name='wororderitem',
            name='part',
            field=models.ForeignKey(blank=True, help_text='Выберите ЗЧ использованную по ЗН', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_order_item_part', to='products.Part', verbose_name='ЗЧ'),
        ),
        migrations.AlterField(
            model_name='wororderitem',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Выберите работу по ЗН', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_order_item_service', to='products.Work', verbose_name='работа'),
        ),
    ]
