# Generated by Django 2.2.24 on 2022-01-06 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_auto_20211124_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wororderitem',
            name='part',
            field=models.ForeignKey(blank=True, help_text='Выберите ЗЧ, использованную по ЗН', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_order_item_part', to='products.Part', verbose_name='ЗЧ'),
        ),
    ]
