# Generated by Django 2.2.24 on 2022-01-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_auto_20220106_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Введите количество', max_digits=12, verbose_name='кол-во'),
        ),
    ]
