# Generated by Django 2.2.24 on 2022-01-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0008_workorderitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Введите количество', max_digits=12, null=True, verbose_name='кол-во'),
        ),
    ]
