# Generated by Django 2.2.24 on 2022-01-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0009_auto_20220107_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='total_out_price_oil',
            field=models.PositiveIntegerField(default=0, help_text='Поле зааполнится автоматически', verbose_name='Стоимость масла грн.'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='total_out_price_parts',
            field=models.PositiveIntegerField(default=0, help_text='Поле зааполнится автоматически', verbose_name='Стоимость ЗЧ грн.'),
        ),
    ]
