# Generated by Django 2.2.20 on 2021-11-06 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Введите название производителя авто (марка)', max_length=100, verbose_name='Марка')),
                ('model', models.CharField(help_text='Введите модель авто', max_length=100, verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_manufacturing', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2021, verbose_name='год выпуска')),
                ('car_number', models.CharField(blank=True, help_text='Введите гос.номер авто', max_length=100, verbose_name='Гос.номер')),
                ('other_char', models.CharField(blank=True, help_text='Введите дополнительную информацию об авто ( цвет, особенности frgg и т.д.)', max_length=100, verbose_name='Другие характеристики')),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_brandmodel', to='cars.BrandModel', verbose_name='Марка-модель')),
            ],
        ),
    ]
