# Generated by Django 2.2.24 on 2021-11-24 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.ForeignKey(blank=True, help_text='выберете владельца авто', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_client', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
