# Generated by Django 2.2.24 on 2021-11-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211106_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmodel',
            options={'verbose_name_plural': 'Марки-модели'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name_plural': 'Машины'},
        ),
        migrations.AddField(
            model_name='car',
            name='motor',
            field=models.CharField(blank=True, help_text='Введите наименование мотора', max_length=100, verbose_name='Мотор'),
        ),
    ]
