# Generated by Django 2.2.24 on 2022-01-06 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20220103_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.ForeignKey(blank=True, help_text='выберете владельца авто', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_client', to='users.ClientProfile', verbose_name='Владелец'),
        ),
    ]
