# Generated by Django 2.2.24 on 2021-11-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20211106_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='motor',
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, help_text='Введите vin', max_length=100, verbose_name='vin-code'),
        ),
    ]
