# Generated by Django 2.2.24 on 2021-11-06 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0004_auto_20211106_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(help_text='выберете владельца авто', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_client', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
