# Generated by Django 2.2.24 on 2021-11-06 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='name',
            field=models.CharField(blank=True, help_text='Введите имя клиента)', max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='введите номер телефона в формате +380671234567', max_length=128, region=None, verbose_name='телефон'),
        ),
    ]
