# Generated by Django 2.2.24 on 2021-11-10 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211106_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='name',
            field=models.CharField(blank=True, help_text='Введите имя клиента', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
